export const DomainRules = {
  MAX_BILHETES: 999999,
  MAX_PROGRESS_PERCENTAGE: 100,
  MAX_VALOR_BILHETES: 100,

  MIN_BILHETES_TOTAIS: 10,
  MIN_BILHETES_COMPRADOS: 0,
  MIN_PROGRESS_PERCENTAGE: 0,
  MIN_VALOR_BILHETES: 0.01,
}
