name: "Artefato da aplicação"

on:
  push:
    branches:
      - "release"
      - "main"
jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/upload-artifact@v3
      with:
        name: Gerar artefato do build
        path: # verificar o path da imagem da aplicação
            
