name: "Build da aplicação"

on:
  pull_request:
    branches:
      - "release"
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Buildar o Docker Compose
      run: docker compose build
      
